### ISSUE TITLE
Css Fix: Main content breaks nav box-shadow

### ISSUE THREAD

**Issue by qborreda** [jayvan/tempest-watch#1]
Just a quick suggestion .. 

At the moment, the navigation box-shadow is broken when the `<main>` content is draw. 
You should just apply a 

``` css
main {
   margin-top: 10px;
}
```

to your main node to fix this ..
